on:
  schedule:
    - cron: '0 1-9 * * *' # every hour between 9 am and 5 pm in hong kong time in utc format
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Check Attendance
        run: node index.js
